import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '../components/Header'
import BackgroundBricks from '../components/BackgroundBricks'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: {
        default: 'Brickers Gallery - AI 레고 작품 갤러리',
        template: '%s | Brickers Gallery',
    },
    description: 'AI로 만든 멋진 레고 작품들을 구경하세요. Explore amazing Lego creations generated by AI.',
    metadataBase: new URL('https://brickers.shop'),
    alternates: {
        canonical: '/gallery',
    },
    openGraph: {
        siteName: 'Brickers',
        type: 'website',
        locale: 'ko_KR',
        url: 'https://brickers.shop/gallery',
        images: [
            {
                url: '/gallery/og-image.png',
                width: 1200,
                height: 630,
                alt: 'Brickers Gallery - AI 레고 작품 갤러리',
            },
        ],
    },
    twitter: {
        card: 'summary_large_image',
        title: 'Brickers Gallery - AI 레고 작품 갤러리',
        description: 'AI로 만든 멋진 레고 작품들을 구경하세요.',
        images: ['/gallery/og-image.png'],
    },
    keywords: ['레고', 'LEGO', 'AI', '브릭', '갤러리', '3D', '조립', 'Brickers'],
    authors: [{ name: 'Brickers' }],
    creator: 'Brickers',
    publisher: 'Brickers',
    robots: {
        index: true,
        follow: true,
        googleBot: {
            index: true,
            follow: true,
            'max-video-preview': -1,
            'max-image-preview': 'large',
            'max-snippet': -1,
        },
    },
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ko">
            <body className={inter.className}>
                <BackgroundBricks />
                <Header />
                <main className="pt-[72px] min-h-screen relative">
                    {children}
                </main>
            </body>
        </html>
    )
}
