import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: {
        default: 'Brickers Gallery - AI 레고 작품 갤러리',
        template: '%s | Brickers Gallery',
    },
    description: 'AI로 만든 멋진 레고 작품들을 구경하세요. Explore amazing Lego creations generated by AI.',
    metadataBase: new URL('https://brickers.shop'),
    alternates: {
        canonical: '/gallery',
    },
    openGraph: {
        siteName: 'Brickers',
        type: 'website',
        locale: 'ko_KR',
        url: 'https://brickers.shop/gallery',
        images: [
            {
                url: '/gallery/og-image.png',
                width: 1200,
                height: 630,
                alt: 'Brickers Gallery - AI 레고 작품 갤러리',
            },
        ],
    },
    twitter: {
        card: 'summary_large_image',
        title: 'Brickers Gallery - AI 레고 작품 갤러리',
        description: 'AI로 만든 멋진 레고 작품들을 구경하세요.',
        images: ['/gallery/og-image.png'],
    },
    keywords: ['레고', 'LEGO', 'AI', '브릭', '갤러리', '3D', '조립', 'Brickers'],
    authors: [{ name: 'Brickers' }],
    creator: 'Brickers',
    publisher: 'Brickers',
    robots: {
        index: true,
        follow: true,
        googleBot: {
            index: true,
            follow: true,
            'max-video-preview': -1,
            'max-image-preview': 'large',
            'max-snippet': -1,
        },
    },
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ko">
            <body className={inter.className}>
                <nav className="w-full h-[72px] flex items-center justify-between px-5 border-b border-[#e0e0e0] bg-white fixed top-0 left-0 z-50">
                    <Link href="/" className="h-12 w-auto cursor-pointer flex items-center">
                        {/* If we can't load the logo easily, use text or external URL */}
                        <span className="text-xl font-bold tracking-tighter">BRICKERS</span>
                    </Link>
                    <div className="flex gap-3">
                        <Link href="https://brickers.shop" className="border-2 border-black rounded-lg px-3 py-1.5 hover:bg-black hover:text-white transition-colors">
                            App으로 이동
                        </Link>
                    </div>
                </nav>
                <main className="pt-[80px] min-h-screen bg-neutral-50">
                    {children}
                </main>
            </body>
        </html>
    )
}
